python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\A.mp4 ..\..\model\data\asl_alphabet_train\A
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\B.mp4 ..\..\model\data\asl_alphabet_train\B
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\C.mp4 ..\..\model\data\asl_alphabet_train\C
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\D.mp4 ..\..\model\data\asl_alphabet_train\D
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\E.mp4 ..\..\model\data\asl_alphabet_train\E
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\F.mp4 ..\..\model\data\asl_alphabet_train\F
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\G.mp4 ..\..\model\data\asl_alphabet_train\G
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\H.mp4 ..\..\model\data\asl_alphabet_train\H
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\I.mp4 ..\..\model\data\asl_alphabet_train\I
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\J.mp4 ..\..\model\data\asl_alphabet_train\J
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\K.mp4 ..\..\model\data\asl_alphabet_train\K
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\L.mp4 ..\..\model\data\asl_alphabet_train\L
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\M.mp4 ..\..\model\data\asl_alphabet_train\M
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\N.mp4 ..\..\model\data\asl_alphabet_train\N
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\O.mp4 ..\..\model\data\asl_alphabet_train\O
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\P.mp4 ..\..\model\data\asl_alphabet_train\P
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\Q.mp4 ..\..\model\data\asl_alphabet_train\Q
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\R.mp4 ..\..\model\data\asl_alphabet_train\R
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\S.mp4 ..\..\model\data\asl_alphabet_train\S
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\T.mp4 ..\..\model\data\asl_alphabet_train\T
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\U.mp4 ..\..\model\data\asl_alphabet_train\U
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\V.mp4 ..\..\model\data\asl_alphabet_train\V
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\W.mp4 ..\..\model\data\asl_alphabet_train\W
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\X.mp4 ..\..\model\data\asl_alphabet_train\X
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\Y.mp4 ..\..\model\data\asl_alphabet_train\Y
python .\script.py ..\..\..\..\fyp_dataset\tarun_asl_signs\Z.mp4 ..\..\model\data\asl_alphabet_train\Z